Рефакторинг инструкции по запуску
moevm/mse_duckietown_dashboard_WEB_Rviz pull request #45
Opened 2022-05-30 16:57 UTC by SonKhwa

2022-06-03 08:01 UTC, NovelCoZ commented
Картинка не на своем месте

![image](https://user-images.githubusercontent.com/31564067/171813665-909f7be2-af41-47a3-9266-bcea7a4f1035.png)

2022-06-03 08:01 UTC, NovelCoZ commented
1. нужно... что?
2. картинка не терминал

![image](https://user-images.githubusercontent.com/31564067/171813746-b0cff4bb-f8dc-47c5-94d9-0ea8d67ac753.png)

2022-06-03 08:02 UTC, NovelCoZ commented
Весь 1 пункт нет красной строки

![image](https://user-images.githubusercontent.com/31564067/171813917-9319e48d-800d-4f01-a690-5d3521547e2b.png)

2022-06-03 08:03 UTC, NovelCoZ commented
/compose/ \compose\

![image](https://user-images.githubusercontent.com/31564067/171814024-1a6c0278-940c-4b24-bde0-192dcb9481ca.png)

2022-06-03 08:03 UTC, NovelCoZ commented
Я просил читать

2022-06-03 08:17 UTC, NovelCoZ commented on README.md
>  # Установка и запуск Duckietown Dashbord:
Разбить на отдельные разделы установку foxglove (два варианта - скачать код и собрать, или скачать образ), и compose - получаем три раздела. Следующий раздел - добавление пакета, затем - раздел запуск (описать, как запускается foxglove, compose, куда переходить чтобы увидеть приложение). Не забывать, что инструкция пишется под ботов - проект будут запускать именно на ботах.

2022-06-03 08:17 UTC, NovelCoZ commented on README.md
> +Примечание: Настройки в \compose\ можно опустить, если изначально установить контейнер webviz на порт 8080, а контейнер compose на другой порт, например, 80, но для этого нужно поменять инструкцию, с
Убрать лишнее

2022-06-03 08:17 UTC, NovelCoZ commented on README.md
> +Выполнить установку /compose/ по инструкции, которая будет выведена на экран после шага(Skip; Next; Finish; Sign in as Developer). Адрес и порт визуализатора настраиваются в настройках \compose\, а и
Подробнее

2022-06-03 08:17 UTC, NovelCoZ commented on README.md
>  # Установка и запуск Duckietown Dashbord:
сейчас в разделе "Установка и запуск Duckietown Dashbord" находится всё кроме добавления пакета

2022-06-03 08:21 UTC, NovelCoZ commented on README.md
> +Выполнить установку /compose/ по инструкции, которая будет выведена на экран после шага(Skip; Next; Finish; Sign in as Developer). Адрес и порт визуализатора настраиваются в настройках \compose\, а и
+ /compose/ \compose\

2022-06-03 11:14 UTC, SonKhwa commented on README.md
> +Примечание: Настройки в \compose\ можно опустить, если изначально установить контейнер webviz на порт 8080, а контейнер compose на другой порт, например, 80, но для этого нужно поменять инструкцию, с
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/pull/45/commits/c69adee2e141d33581b2479c70db3e9418dd3d3e

2022-06-03 11:15 UTC, SonKhwa commented on README.md
> +Примечание: Настройки в \compose\ можно опустить, если изначально установить контейнер webviz на порт 8080, а контейнер compose на другой порт, например, 80, но для этого нужно поменять инструкцию, с
Убрала лишнее

2022-06-03 11:41 UTC, SonKhwa commented on README.md
>  # Установка и запуск Duckietown Dashbord:
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/pull/45/commits/921684893cfe4aea9cb635a13266b3111bb8857b
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/pull/45/commits/d4882ca70d11a5d980696f0c5b6dcad8b5601013
Разбила на отдельные разделы.

2022-06-03 11:43 UTC, SonKhwa commented on README.md
> +Примечание: Настройки в \compose\ можно опустить, если изначально установить контейнер webviz на порт 8080, а контейнер compose на другой порт, например, 80, но для этого нужно поменять инструкцию, с
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/pull/45/commits/9fabae21cb17798782205da27da346b47425e7cd
Убрала лишнее.

2022-06-03 11:46 UTC, SonKhwa commented on README.md
> +Выполнить установку /compose/ по инструкции, которая будет выведена на экран после шага(Skip; Next; Finish; Sign in as Developer). Адрес и порт визуализатора настраиваются в настройках \compose\, а и
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/pull/45/commits/9fabae21cb17798782205da27da346b47425e7cd
Заменила /compose/ на \compose\ и доработала недочеты.

2022-06-03 22:01 UTC, NovelCoZ reviewed
Прошу самостоятельно после исправлений открыть файл README, просмотреть на предмет лишних пробелов, строчек, которые отображаются на одной строке, хотя не должны, пропадающие слеши и т.п.

Изменения также должны быть отображены в документации.

Для того, чтобы поставить \ если он пропадает, нужно его написать дважды. Пишем:
```
\compose\.
\compose\\.
```
Отображается:  
\compose\.  
\compose\\.

2022-06-03 22:15 UTC, NovelCoZ commented
Ссылку на foxglove поменять на форк дмитрия

![image](https://user-images.githubusercontent.com/31564067/171960309-d984daaf-ed32-4dfb-bb47-ac8e44c08d2b.png)

2022-06-03 22:15 UTC, NovelCoZ commented
"Сначала нужно собрать образы... для этого нужно запустить контейнер..." - неправильно

![image](https://user-images.githubusercontent.com/31564067/171960501-a2899f02-8281-4b65-8711-0e5ef88b3613.png)

2022-06-03 22:16 UTC, NovelCoZ commented
\сompose\

![image](https://user-images.githubusercontent.com/31564067/171960655-b38d4bde-2f4a-4575-becc-1cad45d953e8.png)

![image](https://user-images.githubusercontent.com/31564067/171961369-c3f8edde-5b1a-4d2a-ba8f-98443f94aa1d.png)

2022-06-03 22:16 UTC, NovelCoZ commented
Добавить картинку, куда drag-and-drop делать. "При работе с проектом через систему \compose\ диалоговое окно открытия файла не открывается. Вместо использования данной кнопки необходимо воспользоваться drag-and-drop"

![image](https://user-images.githubusercontent.com/31564067/171960751-7821c7fb-e45c-47ff-990d-ce3aeaa672dc.png)

2022-06-04 02:23 UTC, SonKhwa commented on README.md
> +# Установка Duckietown Dashbord:
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/pull/45/commits/7d2b5b7305caeec6b0fae73ab865b2a52876772a
Исправила "Установка Duckietown Dashbord" на "Запуск проекта".

2022-06-04 02:25 UTC, SonKhwa commented on README.md
> +Нужно также установить контейнеры foxglove , \compose\ .
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/pull/45/commits/dfaf4418e12f7f0b8ee015956038c6352c7163e7
Убрала лишний пробел и добавила два пробела для разделения.

2022-06-04 02:27 UTC, SonKhwa commented on README.md
> +Для установки foxglove нужно ввести команду в терминале:
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/pull/45/commits/2f3d4a2a5857f8b34ea8e0e766c49e76bedc2303
Изменила foxglove на \compose\ и добавила слеш.

2022-06-04 02:29 UTC, SonKhwa commented on README.md
> +Рисунок 1.1 - Установка контейнера \compose\ в терминале.
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/pull/45/commits/2f3d4a2a5857f8b34ea8e0e766c49e76bedc2303
Добавила два пробела для переноса строки.

2022-06-04 02:29 UTC, SonKhwa commented on README.md
> +Рисунок 1.2 - Контейнер whitecurl/foxglove в терминале.
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/pull/45/commits/2f3d4a2a5857f8b34ea8e0e766c49e76bedc2303
Добавила два пробела для переноса строки.

2022-06-04 02:31 UTC, SonKhwa commented on README.md
> +Загрузить пакет в Docker-контейнер с системой /compose/ в директорию "/user-data/packages/".
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/pull/45/commits/2f3d4a2a5857f8b34ea8e0e766c49e76bedc2303
Перенесла содержимое в нужное место.

2022-06-04 02:34 UTC, SonKhwa commented on README.md
> +В Docker Desktop перейти во вкладку Containers и открыть CLI терминал контейнера afdaniele/compose. В терминале контейнера ввести:
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/pull/45/commits/2f3d4a2a5857f8b34ea8e0e766c49e76bedc2303
Перенесла инструкцию.

2022-06-04 02:38 UTC, SonKhwa commented on README.md
> +mv mse_duckietown_dashboard_WEB_Rviz ./webviz</code></pre>
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/pull/45/commits/2f3d4a2a5857f8b34ea8e0e766c49e76bedc2303

2022-06-04 02:39 UTC, SonKhwa commented on README.md
> +Рисунок 1.3 - Окно после регистрации в \compose\.
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/pull/45/commits/2f3d4a2a5857f8b34ea8e0e766c49e76bedc2303

2022-06-04 07:37 UTC, SonKhwa commented on README.md
> +Рисунок 1.1 - Установка контейнера \compose\ в терминале.
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/pull/45/commits/9b66153efc177b4187aff7aa51efb8750879c97b

2022-06-04 07:48 UTC, SonKhwa commented on README.md
> +Приложение для визуализации Webviz:
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/pull/45/commits/9b66153efc177b4187aff7aa51efb8750879c97b

2022-06-04 10:07 UTC, NovelCoZ commented on README.md
> +Нужно также установить контейнеры foxglove , \compose\ .
"Для запуска проекта нужно развернуть контейнеры foxglove, \compose\, и добавить в систему \compose\ пакет." вместо "Нужно также установить контейнеры foxglove , \compose\ ."

2022-06-04 10:15 UTC, NovelCoZ commented on README.md
> +Рисунок 1.2 - Контейнер whitecurl/foxglove в терминале.
не исправлено "Рисунок 1.2 - Контейнер whitecurl/foxglove в терминале. [] В Docker Desktop перейти во вкладку Containers и открыть CLI терминал контейнера afdaniele/compose. В терминале контейнера ввести:"

2022-06-04 10:16 UTC, NovelCoZ commented on README.md
> +Загрузить пакет в Docker-контейнер с системой /compose/ в директорию "/user-data/packages/".
не вижу

![image](https://user-images.githubusercontent.com/31564067/171994999-0bb71834-9815-44b2-9e17-7e2172cc569e.png)

2022-06-04 10:17 UTC, NovelCoZ commented on README.md
> +В Docker Desktop перейти во вкладку Containers и открыть CLI терминал контейнера afdaniele/compose. В терминале контейнера ввести:
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/pull/45#discussion_r889442183

2022-06-04 10:18 UTC, NovelCoZ commented on README.md
> +Приложение для визуализации Webviz:
Имелось ввиду это место - "Приложение для визуализации Webviz:".

2022-06-04 10:19 UTC, NovelCoZ commented on README.md
> +Приложение для визуализации Webviz:
"Нажать на кнопку: "Webviz"." д.б. на отдельной строчке

2022-06-04 15:07 UTC, SonKhwa commented on README.md
> +Нужно также установить контейнеры foxglove , \compose\ .
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/66575ab5bb0afed1a8b73f35f89cc1b9f62d042b

2022-06-04 15:09 UTC, SonKhwa commented on README.md
> +Нажать на кнопку: "Webviz".
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/952c880bba5b7108fb24275b15c26731d4bd0455

2022-06-04 15:09 UTC, SonKhwa commented on README.md
> +Рисунок 1.2 - Контейнер whitecurl/foxglove в терминале.
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/952c880bba5b7108fb24275b15c26731d4bd0455

2022-06-04 15:14 UTC, SonKhwa commented on README.md
> +Загрузить пакет в Docker-контейнер с системой /compose/ в директорию "/user-data/packages/".
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/bd0770ac9f2ca751d140b30d5e44cffb5f8cdf6c

2022-06-04 15:15 UTC, SonKhwa commented on README.md
> +В Docker Desktop перейти во вкладку Containers и открыть CLI терминал контейнера afdaniele/compose. В терминале контейнера ввести:
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/bd0770ac9f2ca751d140b30d5e44cffb5f8cdf6c

2022-06-04 15:17 UTC, SonKhwa commented on README.md
> +mv mse_duckietown_dashboard_WEB_Rviz ./webviz</code></pre>
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/375220dd5974a0d00ec4708ad3fdc9ada1fb2a10

2022-06-04 15:18 UTC, SonKhwa commented on README.md
> +Рисунок 1.3 - Окно после регистрации в \compose\.
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/1643d62d431a3215115dc314ad0e05c35f669251

2022-06-04 15:20 UTC, SonKhwa commented on README.md
> +Приложение для визуализации Webviz:
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/fc5b697c3bf21a345b725096a172ab24c0640cfd

2022-06-04 15:20 UTC, SonKhwa commented on README.md
> +Нажать на кнопку: "Webviz".
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/37617e45ff05337fd7af55b91f0ce70a07999a48

2022-06-04 15:21 UTC, SonKhwa commented on README.md
> +Рисунок 1.2 - Контейнер whitecurl/foxglove в терминале.
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/5d1e652ffd51ed8f978f9134fd5898a2185c8155

2022-06-04 15:22 UTC, SonKhwa commented on README.md
> +Рисунок 1.3 - Окно после регистрации в \compose\.
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/321c22e817d6e7d4b30cf75d5c321e7266e0a77a

2022-06-04 15:24 UTC, SonKhwa commented on README.md
> +Затем перейти в браузере по ссылке: http://localhost:8080. Выполнить установку \compose\ по инструкции, которая будет выведена на экран после шага(Skip; Next; Finish; Sign in as Developer). Адрес и п
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/c9de3b09d9600531406b4dc5ecfe51cc3cc49f84

2022-06-04 15:25 UTC, SonKhwa commented on README.md
>  # Добавление пакета Duckietown:
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/96075064f72a947b6b36cf0b0e6a8785012a8d11

2022-06-04 15:27 UTC, SonKhwa commented on README.md
> +Загрузить пакет в Docker-контейнер с системой /compose/ в директорию "/user-data/packages/".
Строка была удалена.

2022-06-04 15:28 UTC, SonKhwa commented on README.md
> +Рисунок 1.1 - Установка контейнера \compose\ в терминале.
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/a8671173f5d9ff875815422065408cbc58dec867

2022-06-04 15:29 UTC, SonKhwa commented on README.md
> +## Установка Foxglove:
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/1728025c5d09b41d97bddaab2f663c41d957029a

2022-06-04 15:29 UTC, SonKhwa commented on README.md
> +Для установки foxglove контейнера нужно ввести команду в терминале:
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/575eec034f5be995ad39faed388ef3a6c73db14b

2022-06-04 15:30 UTC, SonKhwa commented on README.md
> +Сначала нужно собрать образы контейнеров: foxglove , \compose\ :
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/592969069ecc1ef1f79d7235cf527f11c2b1219d

2022-06-04 15:35 UTC, SonKhwa commented on README.md
> +Затем ввести команды в терминале:
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/9e8f33ba40160a5dd17626738d0313fdedb567bf

2022-06-04 15:35 UTC, SonKhwa commented on README.md
> +<pre><code>docker pull whitecurl/foxglove:latest</code></pre>
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/9e8f33ba40160a5dd17626738d0313fdedb567bf

2022-06-04 17:58 UTC, NovelCoZ commented on README.md
> +mv mse_duckietown_dashboard_WEB_Rviz ./webviz</code></pre>
Убрать команду mv, она тут ни к чему

2022-06-04 18:16 UTC, NovelCoZ requested changes

2022-06-04 18:16 UTC, NovelCoZ commented on README.md
> +# Добавление пакета в \compose\\:
Заголовок д.б. второго уровня

2022-06-04 18:16 UTC, NovelCoZ commented on README.md
> +## Установка \compose\\:
Загрузка

2022-06-04 18:16 UTC, NovelCoZ commented on README.md
> +Для установки \compose\ нужно ввести команду в терминале:
Для загрузки

2022-06-04 18:16 UTC, NovelCoZ commented on README.md
> +## Разворачивание контейнера foxglove:
Тоже загрузка

2022-06-04 18:16 UTC, NovelCoZ commented on README.md
> +Для разворачивания foxglove контейнера нужно ввести команду в терминале:
Для загрузки

2022-06-04 18:16 UTC, NovelCoZ commented on README.md
> +Либо ввести команды в терминале:
"Либо клонировать репозиторий foxglove и собрать приложение самостоятельно."

2022-06-04 18:16 UTC, NovelCoZ commented on README.md
> +Запустить контейнер:
Запустить контейнер \compose\:

2022-06-04 18:16 UTC, NovelCoZ commented on README.md
> +![_Y-nOh0YCEEYeDo-e6ZCT-fPEZ6T8LvOvOVNXuJiHzwb4iW6P0qDK_t9d8f1Tv73OusWzyiJWkmbDluJhXGUXlD7](https://user-images.githubusercontent.com/54913485/171691763-7c0f9c1f-53e3-41a2-b835-abd8162efb68.jpg)
поменять на \compose\

2022-06-04 18:16 UTC, NovelCoZ commented on README.md
> +Рисунок 1.2 - Контейнер whitecurl/foxglove в Docker Desktop.
Контейнер \compose\...

2022-06-04 18:16 UTC, NovelCoZ commented on README.md
>  # Запуск проекта:
Подготовка к запуску проекта

2022-06-04 18:16 UTC, NovelCoZ commented on README.md
> +# Запуск Duckietown Dashbord:
"Запуск проекта"

2022-06-04 18:16 UTC, NovelCoZ commented on README.md
> +Сначала нужно собрать образы контейнеров: foxglove, \compose\ :
лишний пробел после \compose\

2022-06-04 18:16 UTC, NovelCoZ commented on README.md
> +mv mse_duckietown_dashboard_WEB_Rviz ./webviz </code></pre>
убрать mv

2022-06-04 18:16 UTC, NovelCoZ commented on README.md
>  В качестве технологий использовались ROS, PHP, REACT, Docker.
\compose\ /compose/

2022-06-04 18:23 UTC, NovelCoZ commented
Не хватает контекста для команд git clone... Написать, зачем вводить команды

![image](https://user-images.githubusercontent.com/31564067/172020662-751beb2b-0197-4701-96ec-902766698e4d.png)

2022-06-04 21:05 UTC, SonKhwa commented on README.md
> +# Добавление пакета в \compose\\:
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/f448418688828de319bf20b05aa0ba2b7460ab8e

2022-06-04 21:06 UTC, SonKhwa commented on README.md
> +## Установка \compose\\:
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/e384e69e7db9e88d37dee7a951818d2b261f607b

2022-06-04 21:06 UTC, SonKhwa commented on README.md
> +Для установки \compose\ нужно ввести команду в терминале:
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/0830d5ce9bf2b18753f67d678034ad6af4172163

2022-06-04 21:07 UTC, SonKhwa commented on README.md
> +## Разворачивание контейнера foxglove:
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/a0b86b1985d46f80e8d3ad2d7661fc9796a1aeed

2022-06-04 21:08 UTC, SonKhwa commented on README.md
> +Для разворачивания foxglove контейнера нужно ввести команду в терминале:
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/0082ca5aa4a7aa4112fac9ef1546aab2ba7e7c19

2022-06-04 21:09 UTC, SonKhwa commented on README.md
> +Либо ввести команды в терминале:
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/130a1601f2363d4cac907e3e103fdd65ed949a45

2022-06-04 21:10 UTC, SonKhwa commented on README.md
> +Запустить контейнер:
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/a26c089365eaa91e67075f23390d44b9a36f9a2b

2022-06-04 21:10 UTC, SonKhwa commented on README.md
> +![_Y-nOh0YCEEYeDo-e6ZCT-fPEZ6T8LvOvOVNXuJiHzwb4iW6P0qDK_t9d8f1Tv73OusWzyiJWkmbDluJhXGUXlD7](https://user-images.githubusercontent.com/54913485/171691763-7c0f9c1f-53e3-41a2-b835-abd8162efb68.jpg)
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/a26c089365eaa91e67075f23390d44b9a36f9a2b

2022-06-04 21:11 UTC, SonKhwa commented on README.md
> +Рисунок 1.2 - Контейнер whitecurl/foxglove в Docker Desktop.
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/a26c089365eaa91e67075f23390d44b9a36f9a2b

2022-06-04 21:11 UTC, SonKhwa commented on README.md
>  # Запуск проекта:
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/d3f9d4c51d2cb60d17d45671e2a033fed6ef1edc

2022-06-04 21:12 UTC, SonKhwa commented on README.md
> +# Запуск Duckietown Dashbord:
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/0f8c04b3c48256bf593f59c7b1b8120bfbbdce84

2022-06-04 21:13 UTC, SonKhwa commented on README.md
> +Сначала нужно собрать образы контейнеров: foxglove, \compose\ :
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/428e6bf237c104fc227bdf6fd462c307d20c315e

2022-06-04 21:13 UTC, SonKhwa commented on README.md
> +mv mse_duckietown_dashboard_WEB_Rviz ./webviz </code></pre>
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/3364e0e9719467bd29bb5e16eb42d0f4bf0d81e7

2022-06-04 21:14 UTC, SonKhwa commented on README.md
>  В качестве технологий использовались ROS, PHP, REACT, Docker.
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/62a66f4ccf3ca23c3b25c1064a4e2168318bed97

2022-06-04 22:31 UTC, NovelCoZ requested changes

2022-06-04 22:31 UTC, NovelCoZ commented on README.md
> +![_Y-nOh0YCEEYeDo-e6ZCT-fPEZ6T8LvOvOVNXuJiHzwb4iW6P0qDK_t9d8f1Tv73OusWzyiJWkmbDluJhXGUXlD7](https://user-images.githubusercontent.com/54913485/171691763-7c0f9c1f-53e3-41a2-b835-abd8162efb68.jpg)
Картинку и подпись к нему

2022-06-04 22:31 UTC, NovelCoZ commented on README.md
> +mv mse_duckietown_dashboard_WEB_Rviz ./webviz </code></pre>
Команду полностью, осталось убрать "mse_duckietown_dashboard_WEB_Rviz ./webviz "

2022-06-04 22:35 UTC, SonKhwa commented on README.md
> +mse_duckietown_dashboard_WEB_Rviz ./webviz </code></pre>
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/f70189a1c4a58a266f7279407bbbfc798f37bbf7
https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz/commit/4860cb415c7f1066cc48684a4308af46e27d81ff

2022-06-04 22:48 UTC, NovelCoZ approved these changes

2022-06-04 22:48 UTC, merged